"""unsure question

Revision ID: 19f69761c936
Revises: b64578134183
Create Date: 2026-04-21 08:31:08.077602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19f69761c936'
down_revision: Union[str, Sequence[str], None] = 'b64578134183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language_parameter_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.String(length=10), nullable=False),
    sa.Column('parameter_id', sa.String(length=10), nullable=False),
    sa.Column('is_unsure', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['parameter_id'], ['parameter_defs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language_id', 'parameter_id', name='uq_lang_param_status')
    )
    op.drop_table('param_types')
    op.drop_table('param_schemas')
    op.drop_table('param_level_of_comparisons')
    op.add_column('examples', sa.Column('transliteration', sa.Text(), nullable=True))
    op.add_column('examples', sa.Column('reference', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('examples', 'reference')
    op.drop_column('examples', 'transliteration')
    op.create_table('param_level_of_comparisons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('label', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('param_level_of_comparisons_pkey')),
    sa.UniqueConstraint('label', name=op.f('param_level_of_comparisons_label_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('param_schemas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('label', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('param_schemas_pkey')),
    sa.UniqueConstraint('label', name=op.f('param_schemas_label_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('param_types',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('label', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('param_types_pkey')),
    sa.UniqueConstraint('label', name=op.f('param_types_label_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('language_parameter_statuses')
    # ### end Alembic commands ###
