"""aggiunti lookups

Revision ID: 592042233b81
Revises: e0bfa064f908
Create Date: 2026-04-21 18:09:20.690002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '592042233b81'
down_revision: Union[str, Sequence[str], None] = 'e0bfa064f908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('param_levels_of_comparison',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_index(op.f('ix_param_levels_of_comparison_id'), 'param_levels_of_comparison', ['id'], unique=False)
    op.create_table('param_schemas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_index(op.f('ix_param_schemas_id'), 'param_schemas', ['id'], unique=False)
    op.create_table('param_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_index(op.f('ix_param_types_id'), 'param_types', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_param_types_id'), table_name='param_types')
    op.drop_table('param_types')
    op.drop_index(op.f('ix_param_schemas_id'), table_name='param_schemas')
    op.drop_table('param_schemas')
    op.drop_index(op.f('ix_param_levels_of_comparison_id'), table_name='param_levels_of_comparison')
    op.drop_table('param_levels_of_comparison')
    # ### end Alembic commands ###
