"""Add Glossary table

Revision ID: 6065ccd6794b
Revises: 67d08cdc597b
Create Date: 2026-04-19 18:24:57.908035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6065ccd6794b'
down_revision: Union[str, Sequence[str], None] = '67d08cdc597b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glossary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word')
    )
    op.create_index(op.f('ix_glossary_id'), 'glossary', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_glossary_id'), table_name='glossary')
    op.drop_table('glossary')
    # ### end Alembic commands ###
