"""Migrazione iniziale pulita

Revision ID: 67d08cdc597b
Revises: 
Create Date: 2026-04-19 15:21:35.695625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67d08cdc597b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parameter_defs',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('implicational_condition', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('schema', sa.String(length=100), nullable=True),
    sa.Column('param_type', sa.String(length=100), nullable=True),
    sa.Column('level_of_comparison', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'user', 'public', name='user_roles'), nullable=True),
    sa.Column('terms_accepted', sa.Boolean(), nullable=True),
    sa.Column('terms_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('languages',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('name_full', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('family', sa.String(length=255), nullable=True),
    sa.Column('top_level_family', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=6), nullable=True),
    sa.Column('historical_language', sa.Boolean(), nullable=True),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('parameter_id', sa.String(length=10), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('is_stop_question', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parameter_id'], ['parameter_defs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.String(length=10), nullable=False),
    sa.Column('question_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('pending', 'waiting_for_approval', 'approved', 'rejected', name='answer_status'), nullable=True),
    sa.Column('response_text', sa.Enum('yes', 'no', name='response_types'), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language_id', 'question_id', name='uq_answer_lang_q')
    )
    op.create_table('language_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.String(length=10), nullable=True),
    sa.Column('parameter_id', sa.String(length=10), nullable=True),
    sa.Column('value_orig', sa.Enum('+', '-', '0', '?', name='param_values_orig'), nullable=True),
    sa.Column('warning_orig', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['parameter_id'], ['parameter_defs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('textarea', sa.Text(), nullable=True),
    sa.Column('gloss', sa.Text(), nullable=True),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language_parameter_evals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_parameter_id', sa.Integer(), nullable=True),
    sa.Column('value_eval', sa.Enum('+', '-', '0', '?', name='param_values_eval'), nullable=True),
    sa.Column('warning_eval', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['language_parameter_id'], ['language_parameters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language_parameter_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('language_parameter_evals')
    op.drop_table('examples')
    op.drop_table('language_parameters')
    op.drop_table('answers')
    op.drop_table('questions')
    op.drop_table('languages')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('parameter_defs')
    # ### end Alembic commands ###
