"""tableA

Revision ID: af7d3a68ac04
Revises: f1efae232089
Create Date: 2026-04-23 11:52:00.782330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af7d3a68ac04'
down_revision: Union[str, Sequence[str], None] = 'f1efae232089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('languages', sa.Column('grp', sa.String(length=255), nullable=True))
    op.add_column('questions', sa.Column('template_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'template_type')
    op.drop_column('languages', 'grp')
    # ### end Alembic commands ###
