"""instructions

Revision ID: b64578134183
Revises: dbc08fbe5c03
Create Date: 2026-04-20 18:59:38.659709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b64578134183'
down_revision: Union[str, Sequence[str], None] = 'dbc08fbe5c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('instruction_yes', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('instruction_no', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'instruction_no')
    op.drop_column('questions', 'instruction_yes')
    # ### end Alembic commands ###
