"""motivations

Revision ID: dbc08fbe5c03
Revises: 82781df11de0
Create Date: 2026-04-20 15:56:05.849549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbc08fbe5c03'
down_revision: Union[str, Sequence[str], None] = '82781df11de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motivations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_motivations_id'), 'motivations', ['id'], unique=False)
    op.create_table('question_allowed_motivations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.String(length=40), nullable=False),
    sa.Column('motivation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['motivation_id'], ['motivations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_allowed_motivations_id'), 'question_allowed_motivations', ['id'], unique=False)
    op.create_table('answer_motivations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('motivation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['motivation_id'], ['motivations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_motivations_id'), 'answer_motivations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answer_motivations_id'), table_name='answer_motivations')
    op.drop_table('answer_motivations')
    op.drop_index(op.f('ix_question_allowed_motivations_id'), table_name='question_allowed_motivations')
    op.drop_table('question_allowed_motivations')
    op.drop_index(op.f('ix_motivations_id'), table_name='motivations')
    op.drop_table('motivations')
    # ### end Alembic commands ###
